services:
  app:
    container_name: "app"
    environment:
      - MONGODB_URL=mongodb://mongo_db/test_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    networks:
      - custom
networks:
  custom:
    driver: bridge